language: node_js
sudo: required
addons:
  chrome: stable
node_js:
  - 10
os: linux
cache:
  yarn: true
branches:
  only:
    - master
    - dev
install:
  - |
    yarn install
script:
  - |
    npm run lint
